### ISSUE TITLE
Naming scheme for AAS objects (identifiables and references) in RDF

### ISSUE THREAD

**Issue by kenwenzel** [admin-shell-io/aas-specs#166]
The AAS specs currently don't define any naming scheme for AAS objects in RDF.
Most examples simply use blank nodes or arbitrary IRIs to name the AAS elements.

At least for `Identifiables` it would be nice if the resource IRI reflects the identification.
Also references to identifiables would benefit from stable resource IRIs in RDF.

The current spec uses strings to encode identifiers (even for IRIs which can natively be represented in RDF):
https://github.com/admin-shell-io/aas-specs/blob/b699cd331e4710380f3d6a4bd7022763c91d2233/schemas/rdf/examples/AAS_Reference_shortExample.ttl#L51

The previous version (which is incorrect according to the current spec) did better:
https://github.com/admin-shell-io/aas-specs/blob/e383ade3c6e45b4c30250e2bbdb484d4e3db2721/schemas/rdf/examples/AAS_Reference_shortExample.ttl#L41

I think it should be discussed if AAS IRIs and IRDIs could be directly represented as native RDF IRIs.

**Comment by mristin** [comment]
@kenwenzel @sebbader I'll close the issue for now. Please re-open if we are to re-consider it for the next version.

@sebbader please decide if you want to take this feature for a future version.[](url)

**Comment by sebbader** [comment]
We need this in the context of distributed shells and querying on them - but not yet in the context of v3.0RC02. We will make a bigger proposal later. Therefore, closing it for now is fine with me.

**Comment by VladimirAlexiev** [comment]
@kenwenzel I wrote https://github.com/admin-shell-io/aas-specs/issues/383 before you pointed me to this one.
It is pretty much the same issue, but mine emphasizes the consequences, which are dire: copying rather than sharing data.

@sebbader This is the biggest blunder of AAS RDF: it uses blank nodes en masse, and represents identifiers in ways that directly go against the Web Architecture, which says: **use URLs**. So:
- You cannot refer between AAS submodels or to other AAS models **directly**, rather you have to use onerous identifier description structures.
- You cannot share "semantic" data between models and submodels, instead you have to copy it locally.
#383 shows how instead of a direct link `s:manufacturer <https://some-company-kg.org/DE/1234567>`
you have to use a complex structure of 3 blank nodes, 16 triples, and an opaque and **unstable** IRDI.
And even with all that complexity, the result is inferior: it captures the manufacturer as **string** (name) rather than as **thing** (a distinct resource).
