### ISSUE TITLE
V3.0RC02 - data specification IEC61360 missing for xml schema?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#194]
I somehow miss the data specification for IEC61360 and the one for physical unit in

https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas/schemas/xml

**Comment by mristin** [comment]
According to the book, they are not part of the meta-model. Moreover, there is no way how we can represent them in the schema unless they are explicitly defined as classes.

Please check off-line with @g1zzm0 .

**Comment by g1zzm0** [comment]
As you can already read in the mapping rules since version RC01: "The schema definitions of the environment are separated by the main aspects in 3 files. AAS Metamodel with in AssetAdministrationShells, Assets, Submodels in AAS.json, Security of the AAS in AAS_ABAC.json, Semantics of the AAS with ConceptDescriptions and DataSpecifications in IEC61360.json."

**Comment by mristin** [comment]
This issue has been fixed by #204.
