### ISSUE TITLE
`MinInterval` and `MaxInterval` without a time zone?

### ISSUE THREAD

**Issue by mristin** [admin-shell-io/aas-specs#245]
This is an issue forked from #244.

Here is the original text:

> @mristin Hey, I had a look again and for lastUpdate you're absolute right. The value is in UTC and because of that should have the Z suffix. But what about minInterval and maxInterval? These values represent intervals and thus it doesn't really make sense that these values are timezoned. IMO they shouldn't have any suffix, what do you think?

If I understand the meta-model correctly, `minInterval` and `maxInterval` represent timestamps as well, so not a time interval (a time interval would be `xs:duration`, while `minInterval` and `maxInterval` are `xs:dateTime`).

@BirgitBoss could you please comment? This is probably a finding to be discussed for the next version?

**Comment by BirgitBoss** [comment]
According to specificication V3.0RC02 the type of BasicEventElement/minInterval and /maxInterval is dateTime and not dateTimeStamp. 

Remark: In the next version of the specification all attributes with type dateTimeStamp will be changed to dateTime because we will restrict types to XML Schema 1.0.



Of course dateTimeStamp is a derived

**Comment by BirgitBoss** [comment]
I checked with @MichaelHoffmeisterFesto : he agrees that it should be xs:duration. 
I will take it is finding to next version to be corrected. Thank you for your input.
