### ISSUE TITLE
[Pt.1] Remove EntityType

### ISSUE THREAD

**Issue by arnoweiss** [admin-shell-io/aas-specs#287]
The Entity-SME currently requires to use the EntityType attribute which can bei either "CoManagedEntity" or "SelfManagedEntity", signifying whether the referred Asset has its own AAS.

![image](https://github.com/admin-shell-io/aas-specs/assets/86715435/698f69e6-b100-4e96-814c-6355757b211d)

Here's the issue:

Someone referring to an asset (for instance in a BOM) **will not always know** if the referred Asset has an AAS or not. There's no way to be sure that an Asset has no AAS. That means everyone modeling an Entity is forced to make a definitive statement which (in most cases) can not be made definitively.

**Comment by BirgitBoss** [comment]
This is true. But if you choose CoManagedEntity you need to provide the information of the Entity within the submodel itself by adding corresponding statements. But it was not yet discussed what happens if the information for the entity is handled in a different submodel. Probably we need to adjust the explanations and/or add a third value "UNKOWN".
