### ISSUE TITLE
[BUG] Different figures with separate titles and numbers display the very same image

### ISSUE THREAD

**Issue by monsieuremre** [admin-shell-io/aas-specs#328]
In the documentation file for Part 3a: Data Specification – IEC 61360 IDTA Number: 01003-a-3-0, Figure 23 and 24 are the same picture. The latter just displays the first ones image directly. This can also be observed when the file is parsed to extract images. There will be one image less than the number of figures, because two figures share the same image.

This is also the case in Part 1: Metamodel IDTA Number: 01001-3-0 with Figures 66 and 67.

Intuitively this seems like a mistake. Are these figures with different titles and descriptions supposed to display the literal same image?

**Comment by BirgitBoss** [comment]
This is a bug in IDTA-01001-3-0 but - as far as I can see - already fixed in https://github.com/admin-shell-io/aas-specs/tree/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/images.
https://github.com/admin-shell-io/aas-specs/blob/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/pages/sharedAnnex/IDTA-01xxx_UML.adoc is the same for all parts of the Specification series, we need to ensure that the newest version is used in all parts.
